version: "3.9"

services:
  db:
    image: postgres:16
    container_name: scholarshelf_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scholarshelf
    ports:
      - "2004:5432" # host:container
    volumes:
      - scholarshelf_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # optional: auto-create tables

volumes:
  scholarshelf_data:
    driver: local
